version: '2'
services:
  db:
    image: postgres
  nginx:
    build: docker/nginx
    depends_on:
      - django
    ports:
      - "80:80"
  redis:
    image: redis:3.0
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: bash -c /django-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh beat
    depends_on:
      - django
      - rabbitmq
    volumes:
      - .:/code
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh worker
    depends_on:
      - django
      - rabbitmq
    volumes:
      - .:/code
  celery_flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh flower
    depends_on:
      - django
      - rabbitmq
    ports:
      - "5555:5555"
    volumes:
      - .:/code
