version: '2'
services:
  db:
    image: postgres:9.6.1
  nginx:
    build: docker/nginx
    depends_on:
      - django
    ports:
      - "80:80"
  redis:
    image: redis:3.0
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "15672:15672"
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /django-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh beat
    depends_on:
      - django
      - rabbitmq
    volumes:
      - .:/code
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: amqp://guest:guest@rabbitmq:5672//
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh worker
    depends_on:
      - django
      - rabbitmq
    volumes:
      - .:/code
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: amqp://guest:guest@rabbitmq:5672//
  celery_flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash /celery-entrypoint.sh flower
    depends_on:
      - django
      - rabbitmq
    ports:
      - "5555:5555"
    volumes:
      - .:/code
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: amqp://guest:guest@rabbitmq:5672//
